<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>YAML.Linter</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MyGame\MyGame.csproj" />
    <ProjectReference Include="..\..\Engine\Engine.Client\Engine.Client.csproj" />
    <ProjectReference Include="..\..\Engine\Engine.Server\Engine.Server.csproj" />
    <ProjectReference Include="..\..\Engine\Engine.Shared\Engine.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputPath>..\..\bin\$(AssemblyName)</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

</Project>
